// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PecuariaApi.Data;

#nullable disable

namespace PecuariaApi.Migrations
{
    [DbContext(typeof(PecuariaDbContext))]
    partial class PecuariaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PecuariaApi.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataNascimento")
                        .HasColumnType("text");

                    b.Property<int?>("MaeId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("NumeroBrinco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<string>("PaiInfo")
                        .HasColumnType("text");

                    b.Property<double?>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NumeroBrinco")
                        .IsUnique();

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("PecuariaApi.Models.ConsumoFeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("QuantidadeFardos")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConsumoFeno");
                });

            modelBuilder.Entity("PecuariaApi.Models.ConsumoRacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("QuantidadeKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConsumoRacao");
                });

            modelBuilder.Entity("PecuariaApi.Models.ConsumoSilagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("QuantidadeToneladas")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ConsumoSilagem");
                });

            modelBuilder.Entity("PecuariaApi.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormaPagamento")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Despesas");
                });

            modelBuilder.Entity("PecuariaApi.Models.Doenca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataCura")
                        .HasColumnType("text");

                    b.Property<string>("DataDiagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeDoenca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tratamento")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Doencas");
                });

            modelBuilder.Entity("PecuariaApi.Models.EstoqueFeno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataProducao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<double?>("PesoFardoKg")
                        .HasColumnType("double precision");

                    b.Property<int>("QuantidadeFardos")
                        .HasColumnType("integer");

                    b.Property<string>("TipoCapim")
                        .HasColumnType("text");

                    b.Property<double?>("ValorTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EstoqueFeno");
                });

            modelBuilder.Entity("PecuariaApi.Models.EstoqueRacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataChegada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fornecedor")
                        .HasColumnType("text");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("QuantidadeKg")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoRacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("ValorKg")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EstoqueRacao");
                });

            modelBuilder.Entity("PecuariaApi.Models.EstoqueSilagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataProducao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Origem")
                        .HasColumnType("text");

                    b.Property<double>("QuantidadeToneladas")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoSilagem")
                        .HasColumnType("text");

                    b.Property<double?>("ValorTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("EstoqueSilagem");
                });

            modelBuilder.Entity("PecuariaApi.Models.LactacaoGalpao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataFim")
                        .HasColumnType("text");

                    b.Property<string>("DataInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("LactacoesGalpao");
                });

            modelBuilder.Entity("PecuariaApi.Models.MedicacaoLactacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarenciaDias")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataLiberacaoManual")
                        .HasColumnType("text");

                    b.Property<string>("DataMedicacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DoseMl")
                        .HasColumnType("double precision");

                    b.Property<int>("LactacaoGalpaoId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeMedicacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<bool>("PodeVenderLeite")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LactacaoGalpaoId");

                    b.ToTable("MedicacoesLactacao");
                });

            modelBuilder.Entity("PecuariaApi.Models.ProducaoLeite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataFim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("LitrosTotal")
                        .HasColumnType("double precision");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProducoesLeite");
                });

            modelBuilder.Entity("PecuariaApi.Models.Propriedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("AreaHectares")
                        .HasColumnType("double precision");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("CnpjCpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Proprietario")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Propriedades");
                });

            modelBuilder.Entity("PecuariaApi.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("PecuariaApi.Models.Reproducao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataConfirmacaoPrenhez")
                        .HasColumnType("text");

                    b.Property<string>("DataInseminacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DataParto")
                        .HasColumnType("text");

                    b.Property<string>("DataPerdaCria")
                        .HasColumnType("text");

                    b.Property<string>("DataPrevistaParto")
                        .HasColumnType("text");

                    b.Property<string>("IdentificacaoSemen")
                        .HasColumnType("text");

                    b.Property<string>("MotivoPerda")
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("RacaSemen")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ValorInseminacao")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Reproducoes");
                });

            modelBuilder.Entity("PecuariaApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PecuariaApi.Models.Vacina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataAplicacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeVacina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("ProximaDose")
                        .HasColumnType("text");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Vacinas");
                });

            modelBuilder.Entity("PecuariaApi.Models.VendaAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataVenda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<double>("PesoKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("ReceitaId")
                        .HasColumnType("integer");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("double precision");

                    b.Property<double>("ValorKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("VendasAnimais");
                });

            modelBuilder.Entity("PecuariaApi.Models.Doenca", b =>
                {
                    b.HasOne("PecuariaApi.Models.Animal", "Animal")
                        .WithMany("Doencas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PecuariaApi.Models.LactacaoGalpao", b =>
                {
                    b.HasOne("PecuariaApi.Models.Animal", "Animal")
                        .WithMany("LactacoesGalpao")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PecuariaApi.Models.MedicacaoLactacao", b =>
                {
                    b.HasOne("PecuariaApi.Models.LactacaoGalpao", "LactacaoGalpao")
                        .WithMany("Medicacoes")
                        .HasForeignKey("LactacaoGalpaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LactacaoGalpao");
                });

            modelBuilder.Entity("PecuariaApi.Models.Reproducao", b =>
                {
                    b.HasOne("PecuariaApi.Models.Animal", "Animal")
                        .WithMany("Reproducoes")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PecuariaApi.Models.Vacina", b =>
                {
                    b.HasOne("PecuariaApi.Models.Animal", "Animal")
                        .WithMany("Vacinas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PecuariaApi.Models.VendaAnimal", b =>
                {
                    b.HasOne("PecuariaApi.Models.Animal", "Animal")
                        .WithMany("Vendas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("PecuariaApi.Models.Animal", b =>
                {
                    b.Navigation("Doencas");

                    b.Navigation("LactacoesGalpao");

                    b.Navigation("Reproducoes");

                    b.Navigation("Vacinas");

                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("PecuariaApi.Models.LactacaoGalpao", b =>
                {
                    b.Navigation("Medicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
